services:
  app-service:
    build:
      context: ./app-service # specify directory where local Dockerfile is located
  auth-service:
    build:
      context: . # use repo root so auth-service-macros is available
      dockerfile: ./auth-service/Dockerfile